"""add role field to user

Revision ID: 2db12587e9f7
Revises: 0f35ed4cbd70
Create Date: 2023-05-18 02:09:28.614166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db12587e9f7'
down_revision = '0f35ed4cbd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('member', 'admin', 'student', 'teacher', name='role'), server_default='member', nullable=False))
        batch_op.alter_column('email_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
